### ISSUE TITLE
Update Wrist-Mk2 model – Let the controller deal with left/right + old/new mech

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-firmware-models#46]
Following up on #45, we're required to update the control model to deal with:
- The left/right wrists.
- The old/new mechanics.

👉🏻📖 Once done, we need to update https://icub-tech-iit.github.io/documentation/wrists/wrist_mk2/?h=wrist.

cc @ale-git @salvi-mattia @valegagge @fiorisi @mfussi66 @Nicogene @marcoaccame

**Comment by ale-git** [comment]
This issue should be fulfilled by https://github.com/robotology/icub-firmware-models/issues/45
