### ISSUE TITLE
Publish and document the model and its codegen for coupling/decoupling ergoCub wrist.

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-firmware-models#5]
Following the [creation of the wrist controller](https://github.com/icub-tech-iit/dev/issues/355) and its [integration in the ems fw](https://github.com/icub-tech-iit/dev/issues/358), we want to publish and document the model and its generated fw for coupling/decoupling of eCub wrist. 

Please see also this [integration](https://github.com/icub-tech-iit/dev/issues/458) activity.

**Comment by ale-git** [comment]
Here it is the PR:
https://github.com/robotology/icub-firmware-models/pull/22

The folder also contains a README.md about the mathematics of the spherical joint.

**Comment by pattacini** [comment]
Thank you @ale-git!

I'll be reviewing the PR asap.

**Comment by pattacini** [comment]
Done via:
- https://github.com/robotology/icub-firmware-models/pull/26
