### ISSUE TITLE
Study the gut of the Supervisor

### ISSUE THREAD

**Issue by Nicogene** [robotology/icub-firmware-models#51]
Get accustomed to all the details of the supervisor.

**Comment by pattacini** [comment]
I think we can close this task 👍🏻 
Feel free to open it up again if needed.

**Comment by mfussi66** [comment]
> I think we can close this task 👍🏻 Feel free to open it up again if needed.

The study was done during this sprint, but most of the knowledge was acquired during development, but yes I agree.
