### ISSUE TITLE
AMCBLDC: supervisorTX doesn't handle the overcurrent flag.

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-firmware-models#58]
While working on issue #40, I noticed that the SupervisorTX supervisorTX doesn't handle the overcurrent flag, while the SupervisorRX performs the check.

| **SupervisorTX**  | **SupervisorRX**  |
|---|---|
|![image](https://github.com/robotology/icub-firmware-models/assets/4233231/3249e210-e413-40a1-9f07-403019d64700)|![image](https://github.com/robotology/icub-firmware-models/assets/4233231/56ddd985-20c6-43c5-9b87-cd319b480ddb)|
|As you can see, in the dictionary, Flafs struct doesn't contain the overcurrentinfo|The Fault handler state machine checks the filtered current value|

I suppose this is a bug, isn't it? @pattacini @mfussi66 

I can fix it before addressing the #40.

**Comment by pattacini** [comment]
Hi @valegagge 

There are many flags in the STATUS that still need to be handled. See #15.
This is one of them.

Once the SV_TX is updated to handle overcurrent, then also the following function requires being updated:

```matlab
function pl = format_status_pck(control_mode, pwm_fbk, flags, shift, CAN_VOLT_REF_SHIFT)

pl = uint8((zeros(8, 1)));

pl(1) = uint8(control_mode);

pl(2) = uint8(0);

tmp1 = bitshift(pwm_fbk, CAN_VOLT_REF_SHIFT - shift);
tmp2 = typecast(tmp1, 'uint8');
pl(3) = tmp2(1);
pl(4) = tmp2(2);

pl(5) = uint8(flags.ExternalFaultAsserted);
pl(6) = uint8(0);
pl(7) = uint8(0);
pl(8) = uint8(0);
```

This function is embedded in https://github.com/robotology/icub-firmware-models/blob/master/boards/amcbldc/messaging/format_can_id.slx.

**Comment by valegagge** [comment]
Hi @pattacini,
I know there are still many status flags to be handled (see #15 ), but this seems an oversight because I remember that some time ago we implemented this functionality. I was suspicious that you had removed it for some reason that I don't know since I'm not on this project for a long time. :)

Anyway, I proceed to fix this issue (taking into account your advice) and then continue with #40. 💪 

thanks!

**Comment by pattacini** [comment]
> I was suspicious that you had removed it for some reason that I don't know since I'm not on this project for a long time. :)

Nope.
Yep, please, go ahead 👍🏻

**Comment by valegagge** [comment]
I annotated here how to address the bug:
1. add the filed `overCurrent` into the `Flag` struct of the dictionary
2. update that field in the `MSG_STATUS_HANDLER`
3. update the former of the status message as @pattacini suggested in the [above comment](https://github.com/robotology/icub-firmware-models/issues/58#issuecomment-1731281403)
4. Perform tests of the supervisor.

**Comment by pattacini** [comment]
As agreed T2T, I'll take over @valegagge for this task.

cc @Nicogene @mfussi66

**Comment by pattacini** [comment]
Tests done and PR successfully merged.
