### ISSUE TITLE
AMCFOC – Extend to AMCFOC the improvements recently applied to AMCBLDC

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-firmware-models#69]
#64 introduced the improvements detailed in https://github.com/robotology/icub-firmware-models/pull/64#issuecomment-1826830847.

We ought to apply them to AMCFOC too.

@mfussi66, I can point you to the relevant options.

cc @Nicogene

**Comment by mfussi66** [comment]
The issue is quite straightforward, the PR is here: https://github.com/robotology/icub-firmware-models/pull/70

Me and @pattacini checked F2F that the trigonometric functions were properly converted to cmsis equivalent, and the codegen report would notify that.

**Comment by pattacini** [comment]
Merged ✅
