### ISSUE TITLE
AMCFOC – Port latest dev from AMCBLDC project

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-firmware-models#74]
This is a follow-up of #73 to address these points below:
- `Vcc` is now an input.
- CMSIS vs. STD variant (it's ok to keep the variant, eventually).
- Variant for the Thermal Model.

cc @Nicogene

**Comment by mfussi66** [comment]
Showing here the modifications I made to address this issue:

>     * `Vcc` is now an input.

Just added Vcc as a input as requested. Sensors is filled from outside the simulink model:

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/0d10b5c2-91ce-4c0e-8aae-1b37c1f326a6)


>     * CMSIS vs. STD variant (it's ok to keep the variant, eventually).

Done ✅

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/1155d6ad-aab0-478d-9ddb-9c57279d7423)

>     * Variant for the Thermal Model.

Similarly to the amcbldc, I created a variant configuration:

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/53fcb84d-3df2-448c-9398-acd9d77d52b1)

Which influences the RMS computation

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/a32bf273-506a-4d96-884f-acc3db8ef79e)

And disables the temperature estimation:

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/0b34d8ba-137c-454e-b138-3fdeb1c0eede)

The referenced model is inside the variant subsystem:

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/9f70ce8e-594a-4e36-9793-50b1968e08dd)

> 
> 
> cc @Nicogene

**Comment by pattacini** [comment]
Nice!

**Comment by mfussi66** [comment]
PR here! #79

**Comment by pattacini** [comment]
Merged ✅
