### ISSUE TITLE
AMCBLDC: Inspect suspect regression in simulation

### ISSUE THREAD

**Issue by mfussi66** [robotology/icub-firmware-models#76]
While working on [AMCFOC Testing](https://github.com/robotology/icub-firmware-models/issues/72) I tried to run a motor control simulation, using the latest `devel` branch. 

To my surprise, the simulated pmsm could not spin because there was no commutation between phases:

![foc_new](https://github.com/robotology/icub-firmware-models/assets/38140169/e8a9a6ff-09b2-4a04-9f5a-9c53e2883671)

We can see that 3-phase currents and voltages remain somewhat constant, while they actually should have this kind of waveform:

Closed loop current control:
![foc_normal](https://github.com/robotology/icub-firmware-models/assets/38140169/51243911-9973-42a5-98b0-2bfbdea38553)

Open loop voltage control:
![voltage_normal](https://github.com/robotology/icub-firmware-models/assets/38140169/c285c8f4-6733-4773-94b9-1c12b052a69f)

So I checked the AMCBLDC project, to verify if upstream everything was working fine.
Most specifically I used the testing model https://github.com/robotology/icub-firmware-models/blob/devel/boards/amcbldc/tests/control/control_pmsm.slx , and I noticed the same behaviour happening starting from the [PR regarding D-axis alignment](https://github.com/robotology/icub-firmware-models/pull/64), even though the physical motor spins with no problem.

I can make some tests to see which changes in this PR affect the simulation.

cc @Nicogene @pattacini @sgiraz

**Comment by pattacini** [comment]
When I said that I used the PMSM model for a test lately, actually I only oversaw the current response, neglecting the speed. Therefore, this can explain why I didn't realize the problem[^1].

Changing the alignment types can be significant for the motor, indeed.

[^1]: Full tests are always helpful 😃

**Comment by pattacini** [comment]
We need to change this, most likely:

![image](https://github.com/robotology/icub-firmware-models/assets/3738070/d54b5d88-dfc3-4817-ad15-572e08719cff)

**Comment by mfussi66** [comment]
You might be right @pattacini , because if I switch back to Q-Axis alignment everything works.

**Comment by pattacini** [comment]
I'm doing some tests for validation.

**Comment by mfussi66** [comment]
> We need to change this, most likely:

Yep, that was it:

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/d672b8f2-f350-49d2-935b-d164877cac9c)

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/baf1cf33-a01b-44fb-a031-f739c2a70a73)

Thanks for the tip @pattacini !

**Comment by pattacini** [comment]
Fixed via:
- #77

**Comment by Nicogene** [comment]
It was fast 😆 
Great debugging indeed 🚀
