### ISSUE TITLE
Perform preliminary firmware tests on the AMC-BLDC

### ISSUE THREAD

**Issue by mfussi66** [robotology/icub-firmware-models#84]
## Task description :memo:
We recently refactored the motor control supervisor (see https://github.com/robotology/icub-firmware-models/issues/65). We now have to test the new architecture on the AMC-BLDC board.
For this we need:
- to restructure the AMC-BLDC architectural model with the new supervisor
- a setup with a motor

## Definition of Done :white_check_mark:
Demo with setup running with the new firmware.

----

Originally opened by @fiorisi in different repo.

----

As suggested by @pattacini, it will be useful to create the AMCBLDC customizations in a separate path, so that the two versions can live side by side.

**Comment by mfussi66** [comment]
The architectural model could become the following:

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/711cbd47-5b8e-4e65-8f29-800a520a5923)

- The supervision is split between motion controller (RX, new version) and base model (TX, coming from amcbldc)
- The messaging remains untouched
- The Motion Controller is instantiated for one motor, and includes
    - FOC
    - Outer control
    - Supervisor RX (new version)
    - Estimation
 
Some considerations:
- One dictionary will win over the other, will it be `common.sldd` or the original AMCBLDC one called `EmbeddedBoard.sldd`? I suggest drawing from `common`
- `errors_rx` and `status_rx` are unused at the moment, maybe it's useful to restore their usage in the new supervisor
- The enums in the motion controller will need to be checked and aligned with the AMCBLDC

**Comment by pattacini** [comment]
All good 👍🏻 

A couple of comments:

>- A global Configuration struct needs to be passed from outside

We should keep adhering to the way we did it on AMCBLDC: a Simulink parameter defined in the dictionary that is used to initialize the internal structures, thus NO dedicated inputs to the architecture.

>- One dictionary will win over the other, will it be common.sldd or the original AMCBLDC one called EmbeddedBoard.sldd? I suggest drawing from common

Definitely `common.sldd` 👍🏻 
Switching back to `EmbeddedBoard.sldd?` makes no sense!

> [!warning]
> Be careful as we shall still deal with the CAN-based part of the dictionaries.

At the moment, this is the dictionary hierarchy:

![Dependency Graph](https://github.com/robotology/icub-firmware-models/assets/3738070/bb53c30d-ca58-4284-9545-fcb53e245ed1)

The dictionary `can_messaging.sldd` needs to be preserved and grafted into `common.sldd` as a child, somehow.

> [!tip]
> Actually, `common.sldd` doesn't sound great 😄
> Any other options?

**Comment by mfussi66** [comment]
> We should keep adhering to the way we did it on AMCBLDC: a Simulink parameter defined in the dictionary that is used to initialize the internal structures, thus NO dedicated inputs to the architecture.

Good point, the GlobalConfiguration includes estimation velocity mode, the lambda for rms computation and so on, not really configurable stuff.

I suggest this dictionary structure:

![image](https://github.com/robotology/icub-firmware-models/assets/38140169/5e7efec4-2f26-4b4c-a311-d5edf3231241)

`amcbldc.sldd` inherits from the other three, and can contain customizations for the board. 
Btw, I am not so sure that `supervisor.sldd` is needed anymore.

**Comment by pattacini** [comment]
>amcbldc.sldd inherits from the other three, and can contain customizations for the board.

Oki 👍🏻 

>Btw, I am not so sure that supervisor.sldd is needed anymore.

Indeed, let's get rid of it 👍🏻 

>The supervisor at the moment cannot support 4 messages (or more generally, events) per tick, but only one.

This appears to be a severe limitation.
We should discuss it.

**Comment by pattacini** [comment]
Nice!

**Comment by mfussi66** [comment]
I created a test sequence in which I send all the "preparation" messages in a tick:

1. limits
2. pid cfg
3. motor cfg
4. control mode set

and on the next tick the control mode was set correctly with the rest of the parameters:

![immagine](https://github.com/robotology/icub-firmware-models/assets/38140169/2b1e730d-11fe-4b84-8fc2-e8f703e4d6c6)

**Comment by pattacini** [comment]
Super!

**Comment by pattacini** [comment]
>That can be done with an additional simulink block, interposed between the two, or by adapting the CAN decoder to the new proposed schema.

We're working in a fully parallel "branch" of development (actually, it's a dedicated folder) meaning that you're dealing with a copy of the current AMCBLDC structures. Hence, it should be safe to adapt the CAN Decoder without impacting what is running now on the boards.

**Comment by mfussi66** [comment]
Today I was able to adapt the CAN decoder so that it could be attached to the new motion controller, and successfully generate the cod, both in C++ 03 and C99 . The signal `status_rx` is not needed anymore  since for each of the max 4 can messages, we now have a enum that specifies that kind of data it is. After it is consumed, it's only needed to reset it to `SupervisorEvents.None`.

**Comment by mfussi66** [comment]
The following commit in my fork allows compilation of the new version of the AMCBLDC: https://github.com/mfussi66/icub-firmware/commit/b0cc008c4aede5976f06fc379921ed8ea0e5e65d . 

Needed steps:
- Change codegen option to `Nonreusable function` so that the `step()` functions did not need to accept arguments
- Add codegen files to keil project
- Adapt glue code so that the updated struct members would be called (it's only name changes)

**Comment by mfussi66** [comment]
A very first test seems promising! Here on the right I am printing the control mode after each can message sent, by reading the `Flags` in the glue code:

![immagine](https://github.com/robotology/icub-firmware-models/assets/38140169/aa433a4e-5509-4f2e-b4c8-e6e27cb9bb11)

For some reason I do not see the FOC and Status messages, I will check.

**Comment by mfussi66** [comment]
Now the CAN messages are sent, because I forgot to set the flag `enable_sending_msg_status`:

![immagine](https://github.com/robotology/icub-firmware-models/assets/38140169/ddff64b2-346a-41ab-ba77-11c44b6acdf9)

However, now they are always sent, I think because there is no reset for the message type (setting it to `supervisorevents.none`) after it is consumed.

**Comment by pattacini** [comment]
>However, now they are always sent, I think because there is no reset for the message type (setting it to supervisorevents.none) after it is consumed.

On the old architecture, I think we have something very similar, although I actually don't remember how we did it.
It may be worth checking it out.

**Comment by mfussi66** [comment]
I think I figured out a way that is a bit more simple and I think elegant: The CAN decoder stateflow chart has an option called "Initialize outputs every time the chart wakes up": if that is enabled, at the beginning of each Ts the outputs are reset to the initial values, which I think is a sensible option for the decoder. 

In C code, this means that the output variables are reinitialized every time `can_decoder()` is called, in the beginning (hopefully it does not cause an important overhead). 

But now it works as expected:

https://github.com/robotology/icub-firmware-models/assets/38140169/b76d38a2-0067-4de3-aaab-1cf658ce8545

**Comment by pattacini** [comment]
Super! Very elegant, indeed.

Perhaps, it could be beneficial to drop a comment somehow in one FSM to bring up this important mechanism of initialization, especially for the newcomers.

**Comment by mfussi66** [comment]
> Perhaps, it could be beneficial to drop a comment somehow in one FSM to bring up this important mechanism of initialization, especially for the newcomers.

Done that. 

After connecting the motor, it does not spin, because the current does not attempt to reach the setpoint. Debugging it at the moment.

**Comment by mfussi66** [comment]
> Perhaps, it could be beneficial to drop a comment somehow in one FSM to bring up this important mechanism of initialization, especially for the newcomers.

Done that. 

After connecting the motor, it does not spin, because the current does not attempt to reach the setpoint. Debugging it at the moment.

**Comment by mfussi66** [comment]
We now have the working current controller, but the motor does not spin:

![immagine](https://github.com/robotology/icub-firmware-models/assets/38140169/1d45dc99-f3b2-4f4d-bb7d-4cb52cc0728d)

> the current does not attempt to reach the setpoint

This was caused by the CAN decoder that would send only a partially set MotorConfiguration struct. Therefore, Vcc and Vmax were = 0.

I solved it by adding the following line on top of the can decoding of the motor config message:

![immagine](https://github.com/robotology/icub-firmware-models/assets/38140169/4930aaa9-4e0a-4700-a428-ec4540c548c9)

**Comment by pattacini** [comment]
Aligned F2F with @mfussi66:
- We need to differentiate the structure used to keep the conf data (that gets initialized via `InitConf`) and the structure used to handle CAN messages.

**Comment by mfussi66** [comment]
> * We need to differentiate the structure used to contain the conf data (that gets initialized via `InitConf`) and the structure used to handle CAN messages.

Yes, I wrapped the elements that can be configured via CAN in a struct called `MotorConfigurationExternals`, which is then included in the global `MotorConfiguration`.

And we now have a spinning motor!
![immagine](https://github.com/robotology/icub-firmware-models/assets/38140169/cc999ace-191f-4b5b-8c23-c903d34f6f7b)

I just need to understand where to put the `hall_sensors_offset` parameter, but I think it can be put in the initial configuration, editable via user-facing script.

**Comment by mfussi66** [comment]
I also fixed a mistake that caused the motor not to be enabled after fault button, now the sequence:
1. fault button pressed
2. fault button released
3. control mode set
4.  target set

is correctly handled, just as before.

**Comment by pattacini** [comment]
>However, setting the FOC Ts to 45us makes the motor spin with more oscillations, is this expected?

Hi @sgiraz 

I don't seem to find the test results we did while checking the performance of the `amcbldc` running with T=45 us. Can you please have a look?

It's important to verify the quality of control.

**Comment by pattacini** [comment]
>However, setting the FOC Ts to 45us makes the motor spin with more oscillations, is this expected?

Hi @mfussi66 

Did you check that the HAL is configured to have the correct PWM rate?

**Comment by mfussi66** [comment]
> >However, setting the FOC Ts to 45us makes the motor spin with more oscillations, is this expected?
> 
> Hi @mfussi66 
> 
> Did you check that the HAL is configured to have the correct PWM rate as well?

Yes, I was rebased on the latest devel which had the changes in the hal and its commits.

I must note that this behaviour seems to be happening also with the devel. Maybe it's just a matter of tuning up the current pod? They have never been touched, even between different motor models.

**Comment by pattacini** [comment]
Ok, I thought you noticed the behavior while switching to Ts = 45 us, whereas it wasn't like that with the previous Ts.

It's true that we can tune the PID gains, but our understanding is that changing Ts doesn't cause any macroscopic change in the logged quantities (e.g., current, position, velocity), keeping conditions (e.g., motor, setup, board) unvaried.

Can you confirm that, @mfussi66, with your current setup?

**Comment by mfussi66** [comment]
> Ok, I thought you noticed the behavior while switching to Ts = 45 us, whereas it wasn't like that with the previous Ts.

That's what I mean, both `devel` and my refactor, with the new Ts, exhibit more oscillations in Current control mode.

I can verify that by trying both devel and refactor with Ts = 45 us and Ts  =26.6 us, in a separate issue.

**Comment by pattacini** [comment]
>I can verify that by trying both devel and refactor with Ts = 45 us and Ts =26.6 us, in a separate issue.

It should be Ts = 37.5 us.

**Comment by mfussi66** [comment]
> > I can verify that by trying both devel and refactor with Ts = 45 us and Ts =26.6 us, in a separate issue.
> 
> Yes, I would do that. It should be Ts = 37.5 us.

Yes my bad, 26.6 (khz) is 1/37.5us .

**Comment by mfussi66** [comment]
When inspecting the control mode switches to finalize the tests on the board, I noticed three occasions that I think are worth attention.

See the plot below:

![changemodes](https://github.com/robotology/icub-firmware-models/assets/38140169/c1b0c285-1fde-44f1-96e9-803c1f909331)

I put arrows on the three events:
- **Switch from Voltage mode to current**: The measured Iq, when put as setpoint as bumpless transition, becomes higher than the measurement

- **Changing from any mode to velocity sets the velocity setpoint to zero**: I think this is expected, since it was like that also in the previous architectural model version

- **Switch from Current mode to Voltage**: In this case, the Vq that is imposed in voltage mode is significantly lower than the Vq that is measured in Current mode: this is most likely caused by this:

![immagine](https://github.com/robotology/icub-firmware-models/assets/38140169/93ba4eb6-83a4-4479-9067-b57b971b665c)

The Vq sent as feedback is scaled by Vcc. But if the same value is set as reference (such as a bumpless change of control mode), the value is scaled by Vmax. If Vmax < Vcc , the applied voltage lowers.

**Comment by mfussi66** [comment]
> **Changing from any mode to velocity sets the velocity setpoint to zero**: I think this is expected, since it was like that also in the previous architectural model version

Working as expected ✔

>   **Switch from Current mode to Voltage**: In this case, the Vq that is imposed in voltage mode is significantly lower than the Vq that is measured in Current mode: this is most likely caused by this:

Targets.voltage needs to be scaled by Vcc and not Vmax.

**Comment by mfussi66** [comment]
And now it works:

![immagine](https://github.com/robotology/icub-firmware-models/assets/38140169/509f4dac-de3b-4f98-8e43-f480d13489f3)

The current looks much worse of course, since it's open loop control. but the Vq is the same.

**Comment by mfussi66** [comment]
> Switch from Voltage mode to current: The measured Iq, when put as setpoint as bumpless transition, becomes higher than the measurement

This is the last point to address: I'll also check if it happens in the original version of the architectural model.

**Comment by mfussi66** [comment]
Indeed, it seems that it happens also with the upstream architectural model, see the video.

Given that this workflow is very unlikely to happen, it might be useful to notify it in a separate issue with low priority.


https://github.com/robotology/icub-firmware-models/assets/38140169/a02650d0-249a-45eb-aac1-281aea560ec8

**Comment by pattacini** [comment]
>Given that this workflow is very unlikely to happen, it might be useful to notify it in a separate issue with low priority.

Agree 👍🏻

**Comment by pattacini** [comment]
Follow-up issue created:
- #86 

I think you can consider this task completed, @mfussi66 🎉

**Comment by mfussi66** [comment]
Ok so I think a recap of the **must have** features is in order:

- [x] Ability to use 3 different control modes: Direct, Current, Velocity (and idle)
- [x] Handling of fault button and mode restore
- [x] 4 can messages handled per tick
- [x]  Bumpless transition between modes

If no feature is missing, I think we can indeed complete the task.

**Comment by mfussi66** [comment]
To conclude this issue, I created these two PRs:

#87 
#88
