### ISSUE TITLE
Setting FOC Ts = 45us creates current oscillations

### ISSUE THREAD

**Issue by mfussi66** [robotology/icub-firmware-models#85]
Setting the FOC Ts to 45us (instead of 37.5us , ndr) makes the motor spin with more oscillations, is this expected?

![immagine](https://github.com/robotology/icub-firmware-models/assets/38140169/50191a3d-3ccb-412c-98af-6074fbe8bdfe)

_Originally posted by @mfussi66 in https://github.com/robotology/icub-firmware-models/issues/84#issuecomment-1983343711_

**Comment by mfussi66** [comment]
This is a test with 45us . Note that with 65mA of target we get close to the no-load current.

![45us](https://github.com/robotology/icub-firmware-models/assets/38140169/f2a77699-e18a-47b9-a16f-cccc20c03653)

Plots with 37.5us to follow asap.

**Comment by mfussi66** [comment]
This is a test with 45us , and the AMC_BLDC architectural model. 

Note that with 65mA of target we get close to the no-load current.


![45us](https://github.com/robotology/icub-firmware-models/assets/38140169/e0c46f63-afd3-43d7-b44a-3721519a0850)


Now with the 37.5us :  

![37_5us](https://github.com/robotology/icub-firmware-models/assets/38140169/8e1a2e30-5f92-4bb7-a419-c0724a4b4ca9)

At a first glance, the behaviour is very much comparable between the two. 

There's only an issue with -65mA, but it's probably due to a missing significant resistant load.

**Comment by pattacini** [comment]
I think that we can reasonably consider the two outcomes very similar 👍🏻 
Thanks for the test, @mfussi66!
