### ISSUE TITLE
Add documentation regarding code generation guidelines

### ISSUE THREAD

**Issue by mfussi66** [robotology/icub-firmware-models#90]
Now that we have achieved some sort of expertise regarding code generation for an embedded board, it might be nice to create a .md document that highlights the best practices and settings to apply for an effective and flexible process.

For example, it could contain:
- Simulink model settings
- CMSIS settings
- Best practices for Simulink blocks
- Stateflow guidelines
- a sprinkle of dictionary usage

**Comment by pattacini** [comment]
Nice idea @mfussi66 👍🏻 

However, the goal is to publish everything, including this aspect, on our website; so, in this sense, it's very much related to:
- #13 

Now that we're in a good position with the development of the architectural models, we can think of addressing the public documentation from the ground up.

Probably, we should put this on the bill for the next facility increment.

**Comment by mfussi66** [comment]
Started a draft in my fork: https://github.com/mfussi66/icub-firmware-models/blob/devel/boards/docs/The%20Techie's%20guide%20to%20code%20generation.md

**Comment by pattacini** [comment]
Great!

Agreed F2F that we eventually aim to develop the website.
In the meantime, we can keep on collecting useful info as markdown files.

**Comment by mfussi66** [comment]
At the moment I am at the _Code generation_ part of the model configuration parameters: https://github.com/mfussi66/icub-firmware-models/blob/devel/boards/docs/The%20Techie's%20guide%20to%20code%20generation.md#code-generation

**Comment by mfussi66** [comment]
In this commit, I think I concluded the draft for the Configuration Parameters window: https://github.com/mfussi66/icub-firmware-models/tree/acc4d9da907b1f4e47e525eedcf1c9d03629a18c

**Comment by pattacini** [comment]
Well done 👍🏻 
I'm a bit overwhelmed these days. I'll try to catch up soon.

**Comment by mfussi66** [comment]
> Well done 👍🏻 I'm a bit overwhelmed these days. I'll try to catch up soon.

No problem! Just posting regular updates to show progress on the task.

**Comment by mfussi66** [comment]
Given the scope of the task, maybe it will be useful to swtich this issue to a first stint?

cc @pattacini

**Comment by pattacini** [comment]
Good point 👍🏻 

I've turned #13 into an Epic and thus associated this issue with that Epic.
Feel free to close this task as complete and open a follow-up to be bundled to the Epic.

**Comment by mfussi66** [comment]
Closing in favour of follow up (to be linked).

**Comment by mfussi66** [comment]
I updated the open post with a checklist of topics addressed in this first sprint @andreaderito .
